export const flags = [
  { emoji: '🇦🇫', name: 'Afghanistan' },
  { emoji: '🇦🇱', name: 'Albania' },
  { emoji: '🇩🇿', name: 'Algeria' },
  { emoji: '🇦🇩', name: 'Andorra' },
  { emoji: '🇦🇴', name: 'Angola' },
  { emoji: '🇦🇬', name: 'Antigua and Barbuda' },
  { emoji: '🇦🇷', name: 'Argentina' },
  { emoji: '🇦🇲', name: 'Armenia' },
  { emoji: '🇦🇺', name: 'Australia' },
  { emoji: '🇦🇹', name: 'Austria' },
  { emoji: '🇦🇿', name: 'Azerbaijan' },
  { emoji: '🇧🇸', name: 'Bahamas' },
  { emoji: '🇧🇭', name: 'Bahrain' },
  { emoji: '🇧🇩', name: 'Bangladesh' },
  { emoji: '🇧🇧', name: 'Barbados' },
  { emoji: '🇧🇾', name: 'Belarus' },
  { emoji: '🇧🇪', name: 'Belgium' },
  { emoji: '🇧🇿', name: 'Belize' },
  { emoji: '🇧🇯', name: 'Benin' },
  { emoji: '🇧🇹', name: 'Bhutan' },
  { emoji: '🇧🇴', name: 'Bolivia' },
  { emoji: '🇧🇦', name: 'Bosnia and Herzegovina' },
  { emoji: '🇧🇼', name: 'Botswana' },
  { emoji: '🇧🇷', name: 'Brazil' },
  { emoji: '🇧🇳', name: 'Brunei' },
  { emoji: '🇧🇬', name: 'Bulgaria' },
  { emoji: '🇧🇫', name: 'Burkina Faso' },
  { emoji: '🇧🇮', name: 'Burundi' },
  { emoji: '🇰🇭', name: 'Cambodia' },
  { emoji: '🇨🇲', name: 'Cameroon' },
  { emoji: '🇨🇦', name: 'Canada' },
  { emoji: '🇨🇻', name: 'Cape Verde' },
  { emoji: '🇨🇫', name: 'Central African Republic' },
  { emoji: '🇹🇩', name: 'Chad' },
  { emoji: '🇨🇱', name: 'Chile' },
  { emoji: '🇨🇳', name: 'China' },
  { emoji: '🇨🇴', name: 'Colombia' },
  { emoji: '🇰🇲', name: 'Comoros' },
  { emoji: '🇨🇬', name: 'Congo' },
  { emoji: '🇨🇷', name: 'Costa Rica' },
  { emoji: '🇭🇷', name: 'Croatia' },
  { emoji: '🇨🇺', name: 'Cuba' },
  { emoji: '🇨🇾', name: 'Cyprus' },
  { emoji: '🇨🇿', name: 'Czech Republic' },
  { emoji: '🇩🇰', name: 'Denmark' },
  { emoji: '🇩🇯', name: 'Djibouti' },
  { emoji: '🇩🇲', name: 'Dominica' },
  { emoji: '🇩🇴', name: 'Dominican Republic' },
  { emoji: '🇪🇨', name: 'Ecuador' },
  { emoji: '🇪🇬', name: 'Egypt' },
  { emoji: '🇸🇻', name: 'El Salvador' },
  { emoji: '🇬🇶', name: 'Equatorial Guinea' },
  { emoji: '🇪🇷', name: 'Eritrea' },
  { emoji: '🇪🇪', name: 'Estonia' },
  { emoji: '🇪🇹', name: 'Ethiopia' },
  { emoji: '🇫🇯', name: 'Fiji' },
  { emoji: '🇫🇮', name: 'Finland' },
  { emoji: '🇫🇷', name: 'France' },
  { emoji: '🇬🇦', name: 'Gabon' },
  { emoji: '🇬🇲', name: 'Gambia' },
  { emoji: '🇬🇪', name: 'Georgia' },
  { emoji: '🇩🇪', name: 'Germany' },
  { emoji: '🇬🇭', name: 'Ghana' },
  { emoji: '🇬🇷', name: 'Greece' },
  { emoji: '🇬🇩', name: 'Grenada' },
  { emoji: '🇬🇹', name: 'Guatemala' },
  { emoji: '🇬🇳', name: 'Guinea' },
  { emoji: '🇬🇼', name: 'Guinea-Bissau' },
  { emoji: '🇬🇾', name: 'Guyana' },
  { emoji: '🇭🇹', name: 'Haiti' },
  { emoji: '🇭🇳', name: 'Honduras' },
  { emoji: '🇭🇺', name: 'Hungary' },
  { emoji: '🇮🇸', name: 'Iceland' },
  { emoji: '🇮🇳', name: 'India' },
  { emoji: '🇮🇩', name: 'Indonesia' },
  { emoji: '🇮🇷', name: 'Iran' },
  { emoji: '🇮🇶', name: 'Iraq' },
  { emoji: '🇮🇪', name: 'Ireland' },
  { emoji: '🇮🇱', name: 'Israel' },
  { emoji: '🇮🇹', name: 'Italy' },
  { emoji: '🇯🇲', name: 'Jamaica' },
  { emoji: '🇯🇵', name: 'Japan' },
  { emoji: '🇯🇴', name: 'Jordan' },
  { emoji: '🇰🇿', name: 'Kazakhstan' },
  { emoji: '🇰🇪', name: 'Kenya' },
  { emoji: '🇰🇮', name: 'Kiribati' },
  { emoji: '🇰🇼', name: 'Kuwait' },
  { emoji: '🇰🇬', name: 'Kyrgyzstan' },
  { emoji: '🇱🇦', name: 'Laos' },
  { emoji: '🇱🇻', name: 'Latvia' },
  { emoji: '🇱🇧', name: 'Lebanon' },
  { emoji: '🇱🇸', name: 'Lesotho' },
  { emoji: '🇱🇷', name: 'Liberia' },
  { emoji: '🇱🇾', name: 'Libya' },
  { emoji: '🇱🇮', name: 'Liechtenstein' },
  { emoji: '🇱🇹', name: 'Lithuania' },
  { emoji: '🇱🇺', name: 'Luxembourg' },
  { emoji: '🇲🇬', name: 'Madagascar' },
  { emoji: '🇲🇼', name: 'Malawi' },
  { emoji: '🇲🇾', name: 'Malaysia' },
  { emoji: '🇲🇻', name: 'Maldives' },
  { emoji: '🇲🇱', name: 'Mali' },
  { emoji: '🇲🇹', name: 'Malta' },
  { emoji: '🇲🇭', name: 'Marshall Islands' },
  { emoji: '🇲🇷', name: 'Mauritania' },
  { emoji: '🇲🇺', name: 'Mauritius' },
  { emoji: '🇲🇽', name: 'Mexico' },
  { emoji: '🇫🇲', name: 'Micronesia' },
  { emoji: '🇲🇩', name: 'Moldova' },
  { emoji: '🇲🇨', name: 'Monaco' },
  { emoji: '🇲🇳', name: 'Mongolia' },
  { emoji: '🇲🇪', name: 'Montenegro' },
  { emoji: '🇲🇦', name: 'Morocco' },
  { emoji: '🇲🇿', name: 'Mozambique' },
  { emoji: '🇲🇲', name: 'Myanmar' },
  { emoji: '🇳🇦', name: 'Namibia' },
  { emoji: '🇳🇷', name: 'Nauru' },
  { emoji: '🇳🇵', name: 'Nepal' },
  { emoji: '🇳🇱', name: 'Netherlands' },
  { emoji: '🇳🇿', name: 'New Zealand' },
  { emoji: '🇳🇮', name: 'Nicaragua' },
  { emoji: '🇳🇪', name: 'Niger' },
  { emoji: '🇳🇬', name: 'Nigeria' },
  { emoji: '🇰🇵', name: 'North Korea' },
  { emoji: '🇲🇰', name: 'North Macedonia' },
  { emoji: '🇳🇴', name: 'Norway' },
  { emoji: '🇴🇲', name: 'Oman' },
  { emoji: '🇵🇰', name: 'Pakistan' },
  { emoji: '🇵🇼', name: 'Palau' },
  { emoji: '🇵🇸', name: 'Palestine' },
  { emoji: '🇵🇦', name: 'Panama' },
  { emoji: '🇵🇬', name: 'Papua New Guinea' },
  { emoji: '🇵🇾', name: 'Paraguay' },
  { emoji: '🇵🇪', name: 'Peru' },
  { emoji: '🇵🇭', name: 'Philippines' },
  { emoji: '🇵🇱', name: 'Poland' },
  { emoji: '🇵🇹', name: 'Portugal' },
  { emoji: '🇶🇦', name: 'Qatar' },
  { emoji: '🇷🇴', name: 'Romania' },
  { emoji: '🇷🇺', name: 'Russia' },
  { emoji: '🇷🇼', name: 'Rwanda' },
  { emoji: '🇰🇳', name: 'Saint Kitts and Nevis' },
  { emoji: '🇱🇨', name: 'Saint Lucia' },
  { emoji: '🇻🇨', name: 'Saint Vincent and the Grenadines' },
  { emoji: '🇼🇸', name: 'Samoa' },
  { emoji: '🇸🇲', name: 'San Marino' },
  { emoji: '🇸🇹', name: 'Sao Tome and Principe' },
  { emoji: '🇸🇦', name: 'Saudi Arabia' },
  { emoji: '🇸🇳', name: 'Senegal' },
  { emoji: '🇷🇸', name: 'Serbia' },
  { emoji: '🇸🇨', name: 'Seychelles' },
  { emoji: '🇸🇱', name: 'Sierra Leone' },
  { emoji: '🇸🇬', name: 'Singapore' },
  { emoji: '🇸🇰', name: 'Slovakia' },
  { emoji: '🇸🇮', name: 'Slovenia' },
  { emoji: '🇸🇧', name: 'Solomon Islands' },
  { emoji: '🇸🇴', name: 'Somalia' },
  { emoji: '🇿🇦', name: 'South Africa' },
  { emoji: '🇰🇷', name: 'South Korea' },
  { emoji: '🇸🇸', name: 'South Sudan' },
  { emoji: '🇪🇸', name: 'Spain' },
  { emoji: '🇱🇰', name: 'Sri Lanka' },
  { emoji: '🇸🇩', name: 'Sudan' },
  { emoji: '🇸🇷', name: 'Suriname' },
  { emoji: '🇸🇪', name: 'Sweden' },
  { emoji: '🇨🇭', name: 'Switzerland' },
  { emoji: '🇸🇾', name: 'Syria' },
  { emoji: '🇹🇼', name: 'Taiwan' },
  { emoji: '🇹🇯', name: 'Tajikistan' },
  { emoji: '🇹🇿', name: 'Tanzania' },
  { emoji: '🇹🇭', name: 'Thailand' },
  { emoji: '🇹🇱', name: 'Timor-Leste' },
  { emoji: '🇹🇬', name: 'Togo' },
  { emoji: '🇹🇴', name: 'Tonga' },
  { emoji: '🇹🇹', name: 'Trinidad and Tobago' },
  { emoji: '🇹🇳', name: 'Tunisia' },
  { emoji: '🇹🇷', name: 'Turkey' },
  { emoji: '🇹🇲', name: 'Turkmenistan' },
  { emoji: '🇹🇻', name: 'Tuvalu' },
  { emoji: '🇺🇬', name: 'Uganda' },
  { emoji: '🇺🇦', name: 'Ukraine' },
  { emoji: '🇦🇪', name: 'United Arab Emirates' },
  { emoji: '🇬🇧', name: 'United Kingdom' },
  { emoji: '🇺🇸', name: 'United States' },
  { emoji: '🇺🇾', name: 'Uruguay' },
  { emoji: '🇺🇿', name: 'Uzbekistan' },
  { emoji: '🇻🇺', name: 'Vanuatu' },
  { emoji: '🇻🇦', name: 'Vatican City' },
  { emoji: '🇻🇪', name: 'Venezuela' },
  { emoji: '🇻🇳', name: 'Vietnam' },
  { emoji: '🇾🇪', name: 'Yemen' },
  { emoji: '🇿🇲', name: 'Zambia' },
  { emoji: '🇿🇼', name: 'Zimbabwe' }
];